//
// Test Bench Module cat_recognizer_lib.fsm_apb_tester.fsm_apb_tester
//
// Created:
//          by - avira.UNKNOWN (DESKTOP-U84L200)
//          at - 19:50:19 11/28/2018
//
// Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
//
`resetall
`timescale 1ns/10ps
module fsm_apb_tester (enable,
                       pclock,
                       psel,
                       penable
                      );

// Local declarations

parameter IDLE = 2'b00;
parameter SETUP = 2'b01;
parameter ENABLE = 2'b10;


input  enable;
output pclock;
output psel;
output penable;

reg pclock;
reg psel;
reg penable;

initial begin
    pclock <= 1'b0;
end

initial begin forever
    #5 pclock = ~pclock;
end

initial begin
   penable <= 1'b0;
   psel    <= 1'b0;
   #5;
   penable <= 1'b0;
   psel    <= 1'b0;
   #10;
   penable <= 1'b0;
   psel    <= 1'b1;
   #10;
   penable <= 1'b1;
   psel    <= 1'b1;
   #10;
   penable <= 1'b0;
   psel    <= 1'b1;
   #10;
   penable <= 1'b1;
   psel    <= 1'b1;
   #10;
   penable <= 1'b0;
   psel    <= 1'b1;
   #10;
   penable <= 1'b1;
   psel    <= 1'b1;
   #10;
   penable <= 1'b0;
   psel    <= 1'b1;
   #10;
   penable <= 1'b1;
   psel    <= 1'b1;
   #10;
   
end

endmodule // fsm_apb_tester