//
// Test Bench Module cat_recognizer_lib.Neuron_tb.Neuron_tester
//
// Created:
//          by - amitb.UNKNOWN (DESKTOP-GIFQ7HQ)
//          at - 13:11:20 08/12/2018
//
// Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
//
`resetall
`timescale 1ns/10ps

module Neuron_tb;

// Local declarations

// Internal signal declarations
wire [7:0]  x;
wire [15:0] w;
wire [31:0] neuron_out;


Neuron U_0(
   .x          (x),
   .w          (w),
   .neuron_out (neuron_out)
);

Neuron_tester U_1(
   .x          (x),
   .w          (w),
   .neuron_out (neuron_out)
);

endmodule // Neuron_tb


