//
// Test Bench Module cat_recognizer_lib.NeuronCalculator_tb.NeuronCalculator_tester
//
// Created:
//          by - amitb.UNKNOWN (DESKTOP-GIFQ7HQ)
//          at - 13:34:34 08/12/2018
//
// Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
//
`resetall
`timescale 1ns/10ps

module NeuronCalculator_tb;

// Local declarations
parameter DATA_WIDTH = 24;
parameter Addr_Depth = 12;
parameter Weight_Percision = 5;

// Internal signal declarations
wire [DATA_WIDTH - 1:0]            x;
wire [3 * Weight_Percision - 1:0] w;
wire                               clock;
wire                               reset;
wire                               enable;
wire                               get_result;
wire                               neuron_calculator_out;


NeuronCalculator #(DATA_WIDTH,Addr_Depth,Weight_Percision) U_0(
   .x                     (x),
   .w                     (w),
   .clock                 (clock),
   .reset                 (reset),
   .enable                (enable),
   .get_result            (get_result),
   .neuron_calculator_out (neuron_calculator_out)
);

NeuronCalculator_tester #(DATA_WIDTH,Addr_Depth,Weight_Percision) U_1(
   .x                     (x),
   .w                     (w),
   .clock                 (clock),
   .reset                 (reset),
   .enable                (enable),
   .get_result            (get_result),
   .neuron_calculator_out (neuron_calculator_out)
);

endmodule // NeuronCalculator_tb


