//
// Test Bench Module cat_recognizer_lib.NeuronCalculator_tester.NeuronCalculator_tester
//
// Created:
//          by - amitb.UNKNOWN (DESKTOP-GIFQ7HQ)
//          at - 13:34:34 08/12/2018
//
// Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
//
`resetall
`timescale 1ns/10ps
module NeuronCalculator_tester (x,
                                w,
                                clock,
                                reset,
                                enable,
                                get_result,
                                neuron_calculator_out
                               );

// Local declarations

parameter DATA_WIDTH = 24;
parameter Addr_Depth = 12;
parameter Weight_Percision = 5;


output x;
output w;
output clock;
output reset;
output enable;
output get_result;
input  neuron_calculator_out;

reg [DATA_WIDTH - 1:0]            x;
reg [3 * Weight_Percision - 1:0] w;
reg                               clock;
reg                               reset;
reg                               enable;
wire                               get_result;
wire                               neuron_calculator_out;

initial begin
    clock <= 1'b0;
	enable <= 1'b1;
	reset <= 1'b1;
	#10 reset <= 1'b0;
	#40 reset <= 1'b1;
	#10 reset <= 1'b0;
    //rst <= 1'b0;
end

initial begin forever
    #5 clock = ~clock;
end

initial begin
   
   x <= 24'h030405;
   w <= 15'b111111111100001;

end

endmodule // NeuronCalculator_tester


